services:
  backend:
    image: diary-backend
    pull_policy: never
    container_name: diary-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - 8000:8000
    env_file:
      ./backend/.env

  frontend:
    image: diary-frontend
    pull_policy: never
    container_name: diary-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  database:
    image: mongo:7.0.14
    container_name: diary-database
    volumes:
      - database-data:/data/db
    env_file:
      - ./database/.env

volumes:
  database-data:
